name: Static Analysis

on:
  push:

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

      - name: run_init
        run: |
          bash .utils/terraform_run_all.sh init docker

      - name: run_test
        run: |
          TAG=nightly
          docker run -v $(pwd):/lint -w /lint ghcr.io/antonbabenko/pre-commit-terraform:$TAG run -a
